### ISSUE TITLE
Many not resolved symbols in Idea + Cursive

### ISSUE THREAD

**Issue by steakoverflow-me** [PEZ/rn-rf-shadow#35]
Hi again!
I have many not resolved symbols, and it spoil interaction with project and even looks bad. Is there any opportunity to fix such behavior?
<img width="1141" alt="Снимок экрана 2022-04-15 в 08 53 32" src="https://user-images.githubusercontent.com/40373781/163513557-28722a0a-8623-4f34-b94a-1411edead947.png">

**Comment by cursive-ide** [comment]
Following the extra step for importing the project as described in [this comment](https://github.com/PEZ/rn-rf-shadow/issues/34#issuecomment-1100582281) will help with the Clojure symbols. The JS interop ones are a known problem which will be fixed shortly. I think this issue can be closed since the fix is the same as #34.
